//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WP8.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WP8.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyday Heroes.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered By Plexus.
        /// </summary>
        public static string ApplicationTitleSub {
            get {
                return ResourceManager.GetString("ApplicationTitleSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  points.
        /// </summary>
        public static string CardViewPointsString {
            get {
                return ResourceManager.GetString("CardViewPointsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card View.
        /// </summary>
        public static string CardViewTitle {
            get {
                return ResourceManager.GetString("CardViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred..
        /// </summary>
        public static string ErrorDefaultMessage {
            get {
                return ResourceManager.GetString("ErrorDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorDefaultTitle {
            get {
                return ResourceManager.GetString("ErrorDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoreboard.
        /// </summary>
        public static string LiveTileExampleBackTitle {
            get {
                return ResourceManager.GetString("LiveTileExampleBackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking: 215
        ///Badges: 3/20
        ///Points: 359.
        /// </summary>
        public static string LiveTileExampleLargeTileContent {
            get {
                return ResourceManager.GetString("LiveTileExampleLargeTileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking: 215
        ///Badges: 3/20
        ///Points: 359.
        /// </summary>
        public static string LiveTileExampleMediumTileContent {
            get {
                return ResourceManager.GetString("LiveTileExampleMediumTileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plexus.
        /// </summary>
        public static string LiveTileExampleTitle {
            get {
                return ResourceManager.GetString("LiveTileExampleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PanoramaItem0Title {
            get {
                return ResourceManager.GetString("PanoramaItem0Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Depot.
        /// </summary>
        public static string PanoramaItem1Title {
            get {
                return ResourceManager.GetString("PanoramaItem1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoreboard.
        /// </summary>
        public static string PanoramaItem2Title {
            get {
                return ResourceManager.GetString("PanoramaItem2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string PanoramaItem3Title {
            get {
                return ResourceManager.GetString("PanoramaItem3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong!.
        /// </summary>
        public static string Wrong {
            get {
                return ResourceManager.GetString("Wrong", resourceCulture);
            }
        }
    }
}
